// ⚠️ DO NOT EDIT THIS FILE ⚠️

import supabase from "./supabase";

async function signUp({ email, password }) {
  return await supabase.auth.signUp({ email, password });
}

async function signIn({ email, password }) {
  return await supabase.auth.signIn({ email, password });
}

async function signOut() {
  return await supabase.auth.signOut();
}

async function restoreUser(token) {
  return await supabase.auth.api.getUser(token);
}

async function getMyMusings() {
  return await supabase
    .from("musings")
    .select("*")
    .eq("author_id", supabase.auth.user().id)
    .order("id", { ascending: false });
}

async function createMusing({ text }) {
  return await supabase
    .from("musings")
    .insert({ text, author_id: supabase.auth.user().id });
}

async function deleteMusing(id) {
  return await supabase.from("musings").delete().eq("id", id);
}

const api = {
  // auth
  signUp,
  signIn,
  signOut,
  restoreUser,

  // musings
  getMyMusings,
  createMusing,
  deleteMusing,
};

export default api;
